version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    restart: always
    environment:
      - PYTHONPATH=/app
    command: streamlit run app.py --server.port 8501
